services:
  - type: web
    name: django-app
    env: python
    buildCommand: ""
    startCommand: gunicorn socialproject.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-db

databases:
  - name: django-db
    plan: free
